//PROGRAM
CREATE DATABASE EMPLOYEEE11;
USE EMPLOYEEE11;

CREATE TABLE Employee(
E_ID INT(25),
E_NAME VARCHAR(25),
AGE INT(10),
SALARY FLOAT(10),
PRIMARY KEY(E_ID)
);
INSERT INTO Employee VALUES (101,"ANU",22,9000);
INSERT INTO Employee VALUES (102,"SHANE",29,8000);
INSERT INTO Employee VALUES (103,"ROHAN",34,6000);
INSERT INTO Employee VALUES (104,"SCOTT",44,10000); 
INSERT INTO Employee VALUES (105,"TIGER",35,8000);
INSERT INTO Employee VALUES (106,"ALEX",27,7000);
INSERT INTO Employee VALUES (107,"ABHI",29,8000);  
SELECT * FROM Employee;

CREATE TABLE CATEGORY(
C_ID VARCHAR(20),
E_NAME VARCHAR(20),
C_NAME VARCHAR(20),
PRIMARY KEY(C_ID)
);
DROP TABLE CATEGORY;
CALL CATEGORYY (101,"ANU",9000);
CALL CATEGORYY (102,"SHANE",8000);
CALL CATEGORYY (103,"ROHAN",6000);
SELECT * FROM CATEGORY;


//SET PROCEDURE

CREATE DEFINER=`root`@`localhost` PROCEDURE `CATEGORYY`(E_ID VARCHAR(25),E_NAME VARCHAR(25),SALARY VARCHAR(10))
BEGIN
IF(SALARY <=5000)
 THEN 
    INSERT INTO CATEGORY VALUES(E_ID,E_NAME,"LEVEL 1");
END IF;
IF(SALARY <=7000)
 THEN
   INSERT INTO CATEGORY VALUES(E_ID,E_NAME,"LEVEL 2");
END IF;
IF(SALARY <=10000)
THEN
  INSERT INTO CATEGORY VALUES(E_ID,E_NAME,"LEVEL 3");
  END IF;
END


//FUNCTION

CREATE DEFINER=`root`@`localhost` FUNCTION `F1`(Experience_level VARCHAR(20),SALARY FLOAT(20)) RETURNS int(11)
BEGIN
if(experience_level = 'Experienced')
then
return(sal+1000);
else
return(sal);
end if;
RETURN 1;
END
