CREATE DATABASE EMP2;
USE EMP2;
SET autocommit = 0;  
START transaction;
CREATE table employee(empno VARCHAR(20) NOT NULL PRIMARY KEY,emp_name VARCHAR(20) NOT NULL,dept VARCHAR(20) NOT NULL,salary INT NOT NULL,dob DATE NOT NULL,branch VARCHAR(20) NOT NULL);
DESCRIBE employee;
INSERT INTO employee VALUES ('E101','Amit','Production',45000,'2000-03-12','Bangalore');
INSERT INTO employee VALUES ('E102','Amit','HR',70000,'2002-07-03','Bangalore');
INSERT INTO employee VALUES ('E103','sunita','Manager',120000,'2001-01-11','Mysore');
INSERT INTO employee VALUES ('E106','Xavier','Manager',120230,'2001-01-11','Mysore');
SAVEPOINT A;
DELETE FROM employee WHERE empno='E106';
SAVEPOINT B;
INSERT INTO employee VALUES ('E130','monson','Manager',120230,'2001-01-11','Mysore');
SAVEPOINT C;
ROLLBACK TO A;
GRANT DELETE ON employee TO 'hai'@'localhost';
REVOKE DELETE ON employee FROM 'hai'@'localhost'; 
REVOKE DELETE ON *.* FROM 'hai'@'localhost';
SHOW GRANTS FOR 'hai'@'localhost';
